// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdAgweEJEMW367IG75DaEBoN59BzL-EZA',
    appId: '1:946204607353:web:bbecb55edd5d345d0125a8',
    messagingSenderId: '946204607353',
    projectId: 'alojago',
    authDomain: 'alojago.firebaseapp.com',
    storageBucket: 'alojago.firebasestorage.app',
    measurementId: 'G-JS74PLEPKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3u-4wzY4xxmE_6xDPR59-y_mg8V6G0RE',
    appId: '1:946204607353:android:ba5ee9335eeb2b8a0125a8',
    messagingSenderId: '946204607353',
    projectId: 'alojago',
    storageBucket: 'alojago.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbLNNZZyTq0OpXluDpXC6_vAocvSm0Xfk',
    appId: '1:946204607353:ios:2fb6f51a8f303dad0125a8',
    messagingSenderId: '946204607353',
    projectId: 'alojago',
    storageBucket: 'alojago.firebasestorage.app',
    iosClientId:
        '946204607353-jldd0mj1g0gi2hu0q70mktiugkv358me.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyec',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbLNNZZyTq0OpXluDpXC6_vAocvSm0Xfk',
    appId: '1:946204607353:ios:2fb6f51a8f303dad0125a8',
    messagingSenderId: '946204607353',
    projectId: 'alojago',
    storageBucket: 'alojago.firebasestorage.app',
    iosClientId:
        '946204607353-jldd0mj1g0gi2hu0q70mktiugkv358me.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdAgweEJEMW367IG75DaEBoN59BzL-EZA',
    appId: '1:946204607353:web:b0a57f6878b2e5570125a8',
    messagingSenderId: '946204607353',
    projectId: 'alojago',
    authDomain: 'alojago.firebaseapp.com',
    storageBucket: 'alojago.firebasestorage.app',
    measurementId: 'G-J4QGF6ZKXX',
  );
}
